site_name: PolyLens
theme:
  name: material
  language: fr
  logo: assets/images/hololens-icon-white.png
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  icon:
    admonition:
      warning: octicons/alert-16
      info: octicons/info-16
  features:
    - navigation.footer
    - content.footnote.tooltips
    - content.tooltips
nav:
  - ğŸ“Œ Accueil: index.md
  - ğŸ“š PrÃ©sentation PolyLens:
    - PrÃ©sentation: presentation/presentation.md
    - Installation: presentation/installation.md
    - Utilisation: presentation/utilisation.md
  - ğŸ› ï¸ CrÃ©er un projet:
    - ğŸ“ƒ PrÃ©requis:
      - TÃ©lÃ©charger les outils/logiciels: prerequis/outils_logiciels.md
      - Prise en main d'Unity: prerequis/unity.md
      - Configurer Visual Studio: prerequis/visual_studio.md
    - âš™ï¸ Configurations:
      - Prise en main du casque: configuration/prise_en_main.md
      - Hololens avec Unity: configuration/developper_avec_unity.md
      - Lancement du projet: configuration/lancement_projet.md
      - Installer Vuforia: configuration/vuforia.md
    - ğŸ’» DÃ©veloppement:
      - Objets manipulables: developpement/objets_manipulables.md
      - Interface utilisateur: developpement/interface_utilisateur.md
      - Utiliser Vuforia: developpement/utiliser_vuforia.md
      - Localisation: developpement/localisation.md
      - Build le projet: developpement/build_projet.md
markdown_extensions:
  - admonition
  - md_in_html
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/WashiFR/Hololens-Doc
repo_name: WashiFR/PolyLens-Doc